### ISSUE TITLE
Missing SITE definition

### ISSUE THREAD

**Issue by kareefardi** [google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu7t5v0#18]
Similar to https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0/issues/16
## Expected Behavior
SITE definition for `GF018hv5v_mcu_sc7` in the tech lefs

## Actual Behavior
No SITE definition

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by QuantamHD** [comment]
this is the correct SITE

```
SITE GF018hv5v_green_sc9
  SYMMETRY X Y ;
  CLASS core ;
  SIZE 0.56 BY 5.04 ;
END GF018hv5v_green_sc9

```

**Comment by proppy** [comment]
shouldn't that be (mcu not green):
```
SITE GF018hv5v_mcu_sc7
  SYMMETRY X Y ;
  CLASS core ;
  SIZE 0.56 BY 3.92 ;
END GF018hv5v_mcu_sc7
```

**Comment by QuantamHD** [comment]
Agreed
